language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --whitelist ./tests --coverage-clover ./coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml
